import DOMPurify, { Config } from "dompurify";

const ALLOWED_TAGS = [
  "a",
  "b",
  "blockquote",
  "br",
  "em",
  "h1",
  "h2",
  "h3",
  "i",
  "li",
  "ol",
  "p",
  "strong",
  "ul",
];

/**
 * These elements are removed with their contents. Other unknown elements are
 * unwrapped so harmless provider wrappers do not make message text disappear.
 */
const DROP_WITH_CONTENT = [
  "audio",
  "base",
  "embed",
  "form",
  "iframe",
  "img",
  "link",
  "math",
  "meta",
  "object",
  "script",
  "source",
  "style",
  "svg",
  "table",
  "template",
  "video",
];

const SANITIZE_CONFIG: Config = {
  ALLOWED_TAGS,
  ALLOWED_ATTR: ["href"],
  ALLOW_ARIA_ATTR: false,
  ALLOW_DATA_ATTR: false,
  ALLOW_UNKNOWN_PROTOCOLS: false,
  ALLOWED_URI_REGEXP: /^(?:https?:\/\/|mailto:)/i,
  FORBID_TAGS: DROP_WITH_CONTENT,
  FORBID_CONTENTS: DROP_WITH_CONTENT,
};

export interface QuotedHtmlParts {
  bodyHtml: string;
  quotedHtml?: string;
}

export interface QuotedContextPart {
  authoredBodyHtml: string;
  publicVisible: boolean;
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function parseBody(html: string): HTMLElement | null {
  if (typeof DOMParser === "undefined") return null;

  try {
    return new DOMParser().parseFromString(html, "text/html").body;
  } catch {
    return null;
  }
}

function canonicalizeHref(rawHref: string): string | undefined {
  // Browsers ignore ASCII whitespace/control characters while resolving a
  // scheme. Remove them for the policy check so `java\nscript:` cannot pass.
  const canonical = Array.from(rawHref.trim())
    .filter((character) => {
      const codePoint = character.codePointAt(0) ?? 0;
      return codePoint > 0x20 && codePoint !== 0x7f;
    })
    .join("");

  if (/^https?:\/\//i.test(canonical)) {
    try {
      const url = new URL(canonical);
      return /^(?:http|https):$/.test(url.protocol) && url.hostname
        ? canonical
        : undefined;
    } catch {
      return undefined;
    }
  }

  return /^mailto:[^:]+$/i.test(canonical) ? canonical : undefined;
}

function normalizeAnchor(anchor: HTMLAnchorElement): void {
  const safeHref = canonicalizeHref(anchor.getAttribute("href") || "");

  for (const attribute of Array.from(anchor.attributes)) {
    anchor.removeAttribute(attribute.name);
  }

  if (!safeHref) return;

  anchor.setAttribute("href", safeHref);
  if (/^https?:/i.test(safeHref)) {
    anchor.setAttribute("target", "_blank");
  }
  anchor.setAttribute("rel", "noopener noreferrer");
}

/**
 * Sanitizes both remote message HTML and locally-created editor HTML with one
 * explicit DOMPurify policy. No caller-specific exception is permitted.
 *
 * If DOM parsing is unavailable, the original value is escaped. That fallback
 * is safe at an HTML sink and displays as plain text instead of attempting to
 * interpret partially-sanitized markup.
 */
export function sanitizeHtml(input: string): string {
  if (!input) return "";

  const body = parseBody(input);
  if (!body) return escapeHtml(input);

  const sanitized = DOMPurify.sanitize(input, SANITIZE_CONFIG);
  const sanitizedBody = parseBody(sanitized);
  if (!sanitizedBody) return escapeHtml(input);

  for (const anchor of Array.from(sanitizedBody.querySelectorAll("a"))) {
    normalizeAnchor(anchor);
  }

  return sanitizedBody.innerHTML;
}

/**
 * The live tenant probe established the first plain blockquote as the only
 * stable quote boundary. Provider class names are intentionally ignored.
 */
export function splitQuotedHtml(input: string): QuotedHtmlParts {
  const sanitized = sanitizeHtml(input);
  const body = parseBody(sanitized);
  if (!body) return { bodyHtml: sanitized };

  const quote = body.querySelector("blockquote");
  if (!quote) return { bodyHtml: sanitized };

  const range = body.ownerDocument.createRange();
  range.setStart(body, 0);
  range.setEndBefore(quote);
  const beforeQuote = body.ownerDocument.createElement("div");
  beforeQuote.appendChild(range.cloneContents());

  return {
    bodyHtml: beforeQuote.innerHTML,
    quotedHtml: quote.innerHTML,
  };
}

/**
 * Treats externally supplied editor content as untrusted draft restoration.
 * A plain blockquote is the probed provider-history boundary, so the quote
 * and everything after it are discarded before the value enters draft state.
 * DOMPurify strips any spoofed marker attributes before boundary detection.
 */
export function sanitizeUntrustedDraftHtml(input: string): string {
  return splitQuotedHtml(input).bodyHtml;
}

function buildPublicHistoryHtml(context: readonly QuotedContextPart[]): string {
  return context
    .filter((part) => part.publicVisible)
    .map((part) => sanitizeHtml(part.authoredBodyHtml))
    .filter(Boolean)
    .join("");
}

/**
 * Recognizes only the history shape generated by this plugin: the final
 * top-level blockquote must exactly equal the structured public context.
 * Authored blockquotes elsewhere remain part of the visible authored body.
 */
export function splitGeneratedReplyHtml(
  input: string,
  context: readonly QuotedContextPart[]
): QuotedHtmlParts {
  const sanitized = sanitizeHtml(input);
  const historyHtml = buildPublicHistoryHtml(context);
  const body = parseBody(sanitized);
  if (!body || !historyHtml) return { bodyHtml: sanitized };

  const nodes = Array.from(body.childNodes);
  let quoteIndex = nodes.length - 1;
  while (
    quoteIndex >= 0 &&
    nodes[quoteIndex].nodeType === 3 &&
    !(nodes[quoteIndex].textContent ?? "").trim()
  ) {
    quoteIndex -= 1;
  }
  const candidate = nodes[quoteIndex];
  const candidateElement = candidate as HTMLElement | undefined;
  if (
    candidateElement?.nodeType !== 1 ||
    candidateElement.tagName.toLowerCase() !== "blockquote" ||
    sanitizeHtml(candidateElement.innerHTML) !== historyHtml
  ) {
    return { bodyHtml: sanitized };
  }

  const authored = body.ownerDocument.createElement("div");
  nodes
    .slice(0, quoteIndex)
    .forEach((node) => authored.appendChild(node.cloneNode(true)));
  return {
    bodyHtml: authored.innerHTML,
    quotedHtml: historyHtml,
  };
}
